Traceback (most recent call last):
  File "/home/codespace/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/codespace/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/codespace/.python/current/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/codespace/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
chart1.configure_view(strokeWidth=0) | chart2
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [43mchart1[49m[38;5;241;43m.[39;49m[43mconfigure_view[49m[43m([49m[43mstrokeWidth[49m[38;5;241;43m=[39;49m[38;5;241;43m0[39;49m[43m)[49m[43m [49m[38;5;241;43m|[39;49m[43m [49m[43mchart2[49m

File [0;32m~/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/altair/vegalite/v5/api.py:1108[0m, in [0;36mTopLevelMixin.__or__[0;34m(self, other)[0m
[1;32m   1106[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(other, TopLevelMixin):
[1;32m   1107[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mOnly Chart objects can be concatenated.[39m[38;5;124m"[39m)
[0;32m-> 1108[0m [38;5;28;01mreturn[39;00m [43mhconcat[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mother[49m[43m)[49m

File [0;32m~/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/altair/vegalite/v5/api.py:3196[0m, in [0;36mhconcat[0;34m(*charts, **kwargs)[0m
[1;32m   3194[0m [38;5;28;01mdef[39;00m [38;5;21mhconcat[39m([38;5;241m*[39mcharts, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m   3195[0m [38;5;250m    [39m[38;5;124;03m"""Concatenate charts horizontally"""[39;00m
[0;32m-> 3196[0m     [38;5;28;01mreturn[39;00m [43mHConcatChart[49m[43m([49m[43mhconcat[49m[38;5;241;43m=[39;49m[43mcharts[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m~/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/altair/vegalite/v5/api.py:3109[0m, in [0;36mHConcatChart.__init__[0;34m(self, data, hconcat, **kwargs)[0m
[1;32m   3105[0m [38;5;129m@utils[39m[38;5;241m.[39muse_signature(core[38;5;241m.[39mTopLevelHConcatSpec)
[1;32m   3106[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, data[38;5;241m=[39mUndefined, hconcat[38;5;241m=[39m(), [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m   3107[0m     [38;5;66;03m# TODO: move common data to top level?[39;00m
[1;32m   3108[0m     [38;5;28;01mfor[39;00m spec [38;5;129;01min[39;00m hconcat:
[0;32m-> 3109[0m         [43m_check_if_valid_subspec[49m[43m([49m[43mspec[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mHConcatChart[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m   3110[0m     [38;5;28msuper[39m(HConcatChart, [38;5;28mself[39m)[38;5;241m.[39m[38;5;21m__init__[39m(data[38;5;241m=[39mdata, hconcat[38;5;241m=[39m[38;5;28mlist[39m(hconcat), [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m   3111[0m     [38;5;28mself[39m[38;5;241m.[39mdata, [38;5;28mself[39m[38;5;241m.[39mhconcat [38;5;241m=[39m _combine_subchart_data([38;5;28mself[39m[38;5;241m.[39mdata, [38;5;28mself[39m[38;5;241m.[39mhconcat)

File [0;32m~/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/altair/vegalite/v5/api.py:2807[0m, in [0;36m_check_if_valid_subspec[0;34m(spec, classname)[0m
[1;32m   2805[0m     val [38;5;241m=[39m spec[38;5;241m.[39mget(attr, Undefined)
[1;32m   2806[0m [38;5;28;01mif[39;00m val [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m Undefined:
[0;32m-> 2807[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(err[38;5;241m.[39mformat(attr, classname))

[0;31mValueError[0m: Objects with "config" attribute cannot be used within HConcatChart. Consider defining the config attribute in the HConcatChart object instead.

